on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: github-webhook
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=ACTIONS_ALLOW_UNSECURE_COMMANDS::true"
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
      - name: Test
        run: echo "${BRANCH_NAME}"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/vives-projectwerk-2021/webhooks-test:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
